"""empty message

Revision ID: a6e6141e24a4
Revises: cb013d825d21
Create Date: 2020-12-13 19:57:17.165207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e6141e24a4'
down_revision = 'cb013d825d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('cover_image', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('avatar_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_image')
    op.drop_column('recipe', 'cover_image')
    # ### end Alembic commands ###
